<?php
    if($page=="customer"){ 
        require_once("modules/customer/views/index.inc.php"); 
    }
    if($page=="user"){ 
        require_once("modules/user/views/index.inc.php"); 
    }
    if($page=="status"){ 
        require_once("modules/status/views/index.inc.php"); 
    }
    if($page=="gateway"){ 
        require_once("modules/gateway/views/index.inc.php"); 
    }
    if($page=="sale"){ 
        require_once("modules/sale/views/index.inc.php"); 
    }
    if($page=="schedule"){ 
        require_once("modules/schedule/views/index.inc.php"); 
    }
    if($page=="notification"){ 
        require_once("modules/notification/views/index.inc.php"); 
    }
    if($page=="invoice"){ 
        require_once("modules/invoice/views/index.inc.php"); 
    }
    if($page=="report"){ 
        require_once("modules/report/views/index.inc.php"); 
    }
    if($page=="report_payment"){ 
        require_once("report/payment/views/index.inc.php"); 
    }
    
?>